-- Bring the migration history back in line with schema.prisma.
--
-- `prisma migrate diff --from-migrations prisma/migrations --to-schema
-- prisma/schema.prisma` printed a non-empty script on main. Two of the three
-- differences are removed here; the third (accounts_issuer_account_id_idx) was
-- right in the migration and is now declared in the schema instead.

-- 20260831120000_remove_leads dropped "LeadEnrichmentJobStatus",
-- "LeadEnrichmentStatus" and "LeadScoringStatus" — the Prisma enum names. The
-- types were created under their @@map names (20260518120000 and
-- 20260519142201), so the IF EXISTS made those three statements silent no-ops
-- and the types outlived their tables. No column uses them: every table that
-- did was dropped by the same migration.
DROP TYPE IF EXISTS "lead_enrichment_job_status";
DROP TYPE IF EXISTS "lead_enrichment_status";
DROP TYPE IF EXISTS "lead_scoring_status";

-- 20260901100000_add_document_versions gave the id a database default the
-- schema never declared. `@default(uuid())` is generated by the Prisma client,
-- as on every other UUID primary key in this schema, none of which has a
-- database default. Nothing inserts into this table outside Prisma.
ALTER TABLE "document_versions" ALTER COLUMN "id" DROP DEFAULT;
