locals {
  secret_name = "${var.release_name}-secrets"
}

resource "kubernetes_namespace" "ragen" {
  metadata {
    name = var.namespace
  }
}

# Written here rather than generated by the chart. The chart's own generation
# is there so `helm install` works on a laptop; for anything long-lived the
# secret has to be recoverable and rotatable from outside the cluster.
resource "kubernetes_secret" "ragen" {
  metadata {
    name      = local.secret_name
    namespace = kubernetes_namespace.ragen.metadata[0].name
  }

  type = "Opaque"
  data = var.secrets
}

resource "helm_release" "ragen" {
  name      = var.release_name
  chart     = var.chart_path
  namespace = kubernetes_namespace.ragen.metadata[0].name

  # Never `true`. The chart annotates the documents PVC and the Secret with
  # `helm.sh/resource-policy: keep`, and creating the namespace here means
  # Terraform already owns it — letting Helm create it too would give two
  # owners for one object.
  create_namespace = false

  atomic          = var.atomic
  timeout         = var.timeout_seconds
  wait            = true
  cleanup_on_fail = true

  values = [for path in var.values_files : file(path)]

  set {
    name  = "existingSecret"
    value = kubernetes_secret.ragen.metadata[0].name
  }

  # Env vars from a secretRef are read once, when the pod starts. Rotating a
  # key here would otherwise change the Secret and leave every pod running
  # with the value it started with — the chart's own checksum covers the
  # ConfigMap, and in `existingSecret` mode it renders no Secret to hash.
  #
  # This is a hash, not the contents: `jsonencode` of a map is key-sorted, so
  # it is stable across plans, and sha256 of it reveals nothing. It does land
  # in state and in the pod annotation, which is why it must stay a digest.
  set {
    name  = "existingSecretChecksum"
    value = sha256(jsonencode(var.secrets))
  }

  set {
    name  = "image.registry"
    value = var.image_registry
  }

  dynamic "set" {
    for_each = var.image_tag == "" ? [] : [var.image_tag]
    content {
      name  = "image.tag"
      value = set.value
    }
  }

  # The Secret has to exist before the migration hook runs, and the hook runs
  # before anything else in the release. The `set` above already creates the
  # dependency, but stating it survives someone rewriting that line.
  depends_on = [kubernetes_secret.ragen]
}
