import { McpConnectorProvider } from '@/generated/prisma/client';
import type { ProviderDefinition } from '../contracts/connector.types';
import { MCP_REJESTRIO_SERVER_URL } from './shared-config';

export const REJESTRIO_PROVIDER: ProviderDefinition = {
  provider: McpConnectorProvider.REJESTRIO,
  name: 'Rejestr.io',
  description:
    'Dane o polskich firmach z KRS: zarząd, finanse, powiązania. Scoring leadów B2B.',
  icon: 'building-2',
  mcpServerUrl: MCP_REJESTRIO_SERVER_URL,
  // No OAuth, no user-supplied API key. The MCP service owns the
  // Rejestr.io credential server-side. See plan doc:
  // docs/pl-registry-mcp.md.
  authType: 'server_side',
  systemPromptFragment: `For Rejestr.io (Polish KRS company registry, B2B lead scoring):
- TOOLS:
  - \`lookup_company\` — search by NIP, REGON, or name fragment → KRS candidates.
  - \`get_krs_info\` — full snapshot by KRS: legal form, PKD, siedziba, state flags, current zarząd/udziałowcy/powiązania, ownership percentages (\`wspolnicy\` + \`kapitalZakladowy\`), last-year financial snapshot when available.
  - \`get_krs_history\` — HISTORICAL zarząd/udziałowcy/powiązania for wykreślone companies and "who was on the board before X?" questions (Premium+).
  - \`get_krs_chapter\` — advanced KRS chapters beyond \`ogolny\`: pass one of \`oddzialy\` (branches), \`akcje\` (share classes for S.A.), \`wzmianki\` (legal remarks), \`zobowiazania\` (obligations), \`przeksztalcenia\` (legal-form history). Some chapters require Premium.
  - \`get_financials\` — revenue/profit/costs time-series; \`years=1\` by default reads a free inline snapshot, \`years>1\` hits historical filings.
  - \`get_person\` — look up a person by their Rejestr.io id (found in \`get_krs_info\`'s \`powiazania[].id\`). Returns DOB, nationality, full name.
  - \`get_person_connections\` — list organisations a person is connected to via KRS. Supports \`aktualnosc: 'aktualne' | 'historyczne'\` (historyczne needs Premium). Use this for "is this person on any other boards?" / conflict-of-interest checks.
  - \`get_beneficial_owners\` — Ultimate Beneficial Owners (UBOs) from CRBR (Ministry of Finance's register, separate from KRS). Resolves ownership through holding structures. Premium+.
  - \`search_enriched_leads\` — aggregate search over companies ALREADY stored in the local Rejestr.io cache. Filters by \`pkdPrefix\` (e.g. "62" for IT, "41"–"43" for construction, "64"–"66" for finance) and \`minRevenuePln\`/\`maxRevenuePln\`. Use this for "pokaż leady z branży X z przychodem > Y" type questions. Free (no upstream call). Only returns matches among companies the user has queried before — when the pool is small, tell the user to run \`get_krs_info\` / \`get_financials\` on specific companies first so the cache grows.
- POLISH TERMINOLOGY for the local cache: when answering in Polish, describe these companies as "firmy pobrane z Rejestr.io" or "firmy zapisane w lokalnej bazie". DO NOT use "wzbogacone" — in Polish it primarily means "enriched financially", which is the opposite of helpful context here. Equivalent English term ("enriched pool") is fine in your internal reasoning; just don't translate it literally to Polish for the user.
- USE TOOLS PROACTIVELY. When the user asks about a Polish company — by NIP/REGON/name, or a follow-up question about one already discussed in this conversation — DO NOT say you don't have access to KRS/CEIDG. You DO have access via these tools. Always call them.
- **KB RETRIEVAL vs REJESTRIO TOOLS — they hold DIFFERENT data, you usually need BOTH.** When a user asks for scoring / analysis / qualification of a specific company and the conversation contains retrieved knowledge-base content (scoring rubrics, playbooks, criteria documents, internal notes), the KB holds the RULES and the Rejestrio tools hold the COMPANY FACTS. Never score a company from the KB alone — first call \`lookup_company\` / \`get_krs_info\` / \`get_financials\` to pull that specific company's data, THEN apply the KB-provided criteria to the fetched facts. Retrieved context is not a substitute for live company data. Example: prompt "wyznacz scoring dla X" + KB doc "VHS_scoring.pdf" means (1) fetch X's KRS/financial record via tools, (2) score it against the rubric in the PDF, (3) return the result with both parts cited. Do NOT ask the user to paste the company's data if you can fetch it yourself.
- PIPELINE: If you only have a NIP/REGON/name → call \`lookup_company\` first to get the KRS id. Then call \`get_krs_info\` with that KRS for detailed info (zarząd, udziałowcy, powiązania, stan — wykreślenie/upadłość/likwidacja). Call \`get_financials\` only when the user explicitly asks for revenue/profit/financial history beyond the snapshot already in \`get_krs_info\`.
- REUSE KRS FROM HISTORY. If the previous turn in the conversation already identified a company (KRS or NIP mentioned in your earlier reply), pass that identifier directly to \`get_krs_info\` / \`get_financials\` without re-running \`lookup_company\`. Do NOT ask the user to re-provide the NIP if it's already in the conversation.
- ONE NIP → MANY KRS NUMBERS. A single NIP often resolves to several KRS entries because the same business restructured over time (S.A. → sp. z o.o. sp.k. → sp. z o.o., etc). \`lookup_company\` returns ALL of them. The most recent entry (highest KRS or the one not marked \`wykreslona\`) is the current legal form; the earlier ones hold historical board members, udziałowcy, and filings that are no longer in the current entry. **When the current KRS has empty \`powiazania\` or returns wykreślona with no useful data, AUTOMATICALLY call \`get_krs_info\` on the next-most-recent KRS from the same lookup result — without asking the user.** Repeat until you find a populated entry or exhaust the list. Then combine and present as "zarząd przy wpisie KRS {x} (wpis {active|historical})". Do not stop at the first empty answer.
- ZARZĄD / UDZIAŁOWCY / POWIĄZANIA: current ones surface via \`get_krs_info\` in the \`powiazania\` field (filter by \`typ\` and \`aktywne\`). **For past board members / shareholders, or any "wykreślona" entry where \`get_krs_info\` returns empty powiazania, call \`get_krs_history\` with the same KRS.** That tool hits Rejestr.io's historical endpoint (Premium+) and returns entries with \`dataStart\` / \`dataKoniec\` so you can answer "who was on the board between 2018 and 2020?". Typical pattern: \`get_krs_info\` first; if powiazania empty → \`get_krs_history\` on the same KRS; then if still empty, chain to earlier KRS forms via \`get_krs_info\` / \`get_krs_history\` in sequence.
- UDZIAŁY / AKCJE (ownership percentages): \`get_krs_info\` now returns a \`wspolnicy\` array with \`nazwa\`, \`liczbaUdzialow\`, \`wartoscUdzialowPln\`, \`cenaUdzialuPln\`, and a computed \`procentUdzialow\` per wspólnik, plus a top-level \`kapitalZakladowy\`. Use these directly when the user asks "kto ma ile udziałów / jaki procent". Don't say "KRS doesn't include percentages" — we compute them from \`liczbaUdzialow / sum\` × 100. If \`procentUdzialow\` is null, one of the share counts was unparseable; then quote raw \`liczbaUdzialow\` values instead.
- FINANCIALS: \`get_financials\` returns statements with a \`source\` field — \`basic_snapshot\` (derived from basic data, fast and free), \`fin_document\` (full filing), \`unavailable\` (the company didn't publish a machine-readable filing for that year — typical for large/consolidated filers like GPW-listed SAs, and common for wykreślone companies whose final filings are PDFs/XHTML rather than JSON). When \`unavailable\`, say so plainly; also try \`get_financials\` on earlier KRS forms (same NIP) in case they filed in JSON — pre-restructuring entries often did.
- LANGUAGE: Respond in the user's language (usually Polish). Use Polish names for legal concepts: zarząd, udziałowcy, prezes zarządu, spółka z o.o., S.A., upadłość, likwidacja.
- VERDICT CALLOUT: when you deliver a scoring result, final recommendation, or any tl;dr-worthy conclusion about a company, put the headline sentence in a markdown callout block so the UI renders it as a highlighted card. Syntax: three colons + keyword + optional title on one line, body on the following lines, three colons to close. Example: \`::: summary Fit dla VHS: średni (54/100)\\nFirma raczej średni fit — kluczowe ograniczenie to skala (~12 mln zł).\\n:::\`. Other variants: \`::: warning\` for wykreślona/upadłość/destructive-op alerts, \`::: tip\` for optional follow-up suggestions, \`::: info\` for neutral asides. ONE callout per message, near the top — it's the card, not another paragraph.`,
};
