FROM mcr.microsoft.com/presidio-analyzer:latest

RUN pip install --no-cache-dir \
    https://github.com/explosion/spacy-models/releases/download/pl_core_news_md-3.8.0/pl_core_news_md-3.8.0-py3-none-any.whl

WORKDIR /app

# Rename original app.py so our custom app.py can import it as _presidio_app
RUN mv /app/app.py /app/_presidio_app.py

COPY recognizers/ /app/recognizers/
COPY app.py /app/app.py
COPY conf/nlp.yaml /app/presidio_analyzer/conf/default.yaml
COPY conf/analyzer.yaml /app/presidio_analyzer/conf/default_analyzer.yaml
COPY conf/recognizers.yaml /app/presidio_analyzer/conf/default_recognizers.yaml

ENV RECOGNIZERS_PATH=/app/recognizers

CMD ["sh", "-c", "poetry run gunicorn -w \"${WORKERS:-1}\" -b \"0.0.0.0:${PORT:-3000}\" \"app:create_app()\""]

EXPOSE 3000
