import { test, expect } from '@playwright/test';

import { AUTH_FILE, TEST_ORG_ID, TEST_USER_ID } from './constants';
import { ROUTES } from './helpers';

test.use({ storageState: AUTH_FILE });

/**
 * A connector that exists only as a row — no manifest, no behaviour pack, no
 * deploy — is offered to a user and can be connected.
 *
 * That is ADR-52's whole claim, and every other connector spec tests it
 * against one of the eleven *built-ins*, which have a manifest behind them and
 * so prove the opposite of what they look like they prove. `p0-30` uses
 * `SLACK` and `CLICKUP`; `p1-33` uses built-ins too. If the behaviour-pack
 * lookup started returning `undefined` for an unknown slug and something
 * downstream threw, both of those would stay green and no customer could ever
 * use a connector their operator added.
 *
 * It is also the regression gate for the wire contract
 * `create-ragen-connector` generates against — see ADR-07 in
 * webamigos/ragen-connectors. The templates can only test their own assertion
 * of that contract; this is the side that can test the contract.
 *
 * `p0-` on purpose. A pull request runs only `smoke-*` and `p0-*`, so a
 * `p1`–`p3` test would not gate the change that breaks this.
 *
 * **What this deliberately does not do is open an MCP session.** The address
 * policy refuses loopback whatever `allowsPrivateAddress` says — by design,
 * because cloud metadata lives on link-local — so a stub server on `127.0.0.1`
 * is unreachable to the app by construction, and one on the machine's LAN
 * address makes the test depend on the host's network. The two halves that
 * *can* be pinned down deterministically are pinned down elsewhere, and named
 * here so nobody adds a flaky third:
 *   - the scheme threaded to the transport —
 *     `src/libs/mcp/__tests__/connect-is-guarded.test.ts` and its apps/api
 *     sibling;
 *   - the address policy itself — `packages/connector-guard`.
 */
async function withPrisma<T>(fn: (prisma: any) => Promise<T>): Promise<T> {
  const { PrismaClient } = await import('../src/generated/prisma/client');
  const { PrismaPg } = await import('@prisma/adapter-pg');
  const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
  const prisma = new PrismaClient({ adapter });
  try {
    return await fn(prisma);
  } finally {
    await prisma.$disconnect();
  }
}

/**
 * Lowercase-kebab, as every entry created from now on must be — the eleven
 * built-ins SHOUT because vault paths and `customerId`s already hold those
 * strings, and a new slug that collided with one case-insensitively would send
 * both connectors the same `x-customer-id`.
 */
const SLUG = 'e2e-weather';
const LABEL = 'E2E Weather';

/**
 * Deliberately `http://` and on RFC 1918 space: the shape an operator's own
 * MCP server takes on an internal network, and the one that used to be
 * accepted by the form, reported working by Test connection, and refused at
 * every tool load.
 */
const MCP_URL = 'http://10.99.0.5:9005/mcp';

let previousAllowed: string[] = [];
let settingsExisted = false;

test.beforeAll(async () => {
  await withPrisma(async (prisma) => {
    await prisma.mcpCatalogEntry.upsert({
      where: { slug: SLUG },
      update: {
        mcpServerUrl: MCP_URL,
        enabled: true,
        allowsPrivateAddress: true,
      },
      create: {
        slug: SLUG,
        label: LABEL,
        description: 'Generated by create-ragen-connector.',
        lucideIcon: 'cloud-sun',
        mcpServerUrl: MCP_URL,
        authType: 'SERVER_SIDE',
        allowsPrivateAddress: true,
        isBuiltIn: false,
        enabled: true,
      },
    });

    // The allowlist is empty-means-all, but this suite shares one database and
    // another spec may have narrowed it. Read it, widen it, put it back.
    const settings = await prisma.organizationSettings.findUnique({
      where: { organizationId: TEST_ORG_ID },
      select: { allowedConnectors: true },
    });
    settingsExisted = settings !== null;
    previousAllowed = settings?.allowedConnectors ?? [];

    if (previousAllowed.length > 0) {
      await prisma.organizationSettings.update({
        where: { organizationId: TEST_ORG_ID },
        data: { allowedConnectors: [...previousAllowed, SLUG] },
      });
    }
  });
});

test.afterAll(async () => {
  await withPrisma(async (prisma) => {
    await prisma.mcpConnector.deleteMany({
      where: { organizationId: TEST_ORG_ID, providerSlug: SLUG },
    });
    await prisma.mcpCatalogEntry.deleteMany({ where: { slug: SLUG } });

    if (!settingsExisted) {
      return;
    }
    await prisma.organizationSettings.update({
      where: { organizationId: TEST_ORG_ID },
      data: { allowedConnectors: previousAllowed },
    });
  });
});

test.describe('a connector that is only a catalogue row', () => {
  test('is offered to a user with no manifest behind it', async ({ page }) => {
    await page.goto(ROUTES.settingsConnectors);
    await expect(
      page.getByRole('heading', { name: /integracje/i }),
    ).toBeVisible({ timeout: 10_000 });

    await expect(
      page.getByText(LABEL).first(),
      'an entry an operator added should be offered like any other',
    ).toBeVisible({ timeout: 10_000 });
  });

  test('connects from the card, and the connector names the row it came from', async ({
    page,
  }) => {
    // Through the card, not by importing the command: a `'use server'` module
    // pulled into Playwright's own runner resolves none of the app's aliases
    // and would be testing a different module graph than the one that ships.
    await page.goto(ROUTES.settingsConnectors);
    await expect(
      page.getByRole('heading', { name: /integracje/i }),
    ).toBeVisible({ timeout: 10_000 });

    // `server_side` has no consent screen and no credentials dialog: the card
    // creates the row and flips it straight to CONNECTED.
    const card = page
      .locator('div')
      .filter({ hasText: LABEL })
      .locator('button', { hasText: /^Połącz$/ })
      .last();
    await card.click();

    await expect(
      page.getByText(/Połączono/).first(),
      'a server_side entry connects without a consent screen',
    ).toBeVisible({ timeout: 15_000 });

    await withPrisma(async (prisma) => {
      const connector = await prisma.mcpConnector.findUnique({
        where: {
          organizationId_userId_providerSlug: {
            organizationId: TEST_ORG_ID,
            userId: TEST_USER_ID,
            providerSlug: SLUG,
          },
        },
        select: {
          providerSlug: true,
          customerId: true,
          mcpServerUrl: true,
        },
      });

      expect(
        connector,
        'an enabled catalogue entry should be connectable',
      ).not.toBeNull();

      // `{orgId}:{userId}:{slug.toLowerCase()}` — the string the connector
      // sends as `x-customer-id` and the one its vault token path is keyed on.
      expect(connector.customerId).toBe(
        `${TEST_ORG_ID}:${TEST_USER_ID}:${SLUG}`,
      );

      // The row's URL, unchanged. It already ends in `/mcp`, so nothing is
      // appended — and a row that did *not* end in `/mcp` would be stored with
      // the suffix and dialled without it, which is why the generated README
      // prints the full endpoint.
      expect(connector.mcpServerUrl).toBe(MCP_URL);
      expect(connector.providerSlug).toBe(SLUG);
    });
  });

  test('stops being offered the moment the entry is disabled', async ({
    page,
  }) => {
    // The switch an operator has instead of a feature flag. It has to beat
    // both the allowlist and an existing connector row.
    await withPrisma(async (prisma) => {
      await prisma.mcpCatalogEntry.update({
        where: { slug: SLUG },
        data: { enabled: false },
      });
    });

    try {
      await page.goto(ROUTES.settingsConnectors);
      await expect(
        page.getByRole('heading', { name: /integracje/i }),
      ).toBeVisible({ timeout: 10_000 });

      await expect(
        page.getByText(LABEL),
        'a disabled entry reaches nobody, connected or not',
      ).toHaveCount(0);
    } finally {
      await withPrisma(async (prisma) => {
        await prisma.mcpCatalogEntry.update({
          where: { slug: SLUG },
          data: { enabled: true },
        });
      });
    }
  });
});
