-- Add lead scoring step values to AiUsageStep enum
ALTER TYPE "AiUsageStep" ADD VALUE IF NOT EXISTS 'LEAD_SCORING_CRITERION';
ALTER TYPE "AiUsageStep" ADD VALUE IF NOT EXISTS 'LEAD_SCORING_DISQUALIFIER';
ALTER TYPE "AiUsageStep" ADD VALUE IF NOT EXISTS 'LEAD_SCORING_SINGLE_PROMPT';
