#!/usr/bin/env bash
#
# Generates the Compose override that puts node_modules and every workspace's
# build output in a named Docker volume instead of on the bind mount.
#
# Why generated rather than written by hand: the list is one entry per
# workspace, and this repository has already been bitten several times by a
# hand-maintained list that nobody updated when a workspace was added
# (tests/architecture/lint-staged-covers-every-workspace.test.ts exists for
# exactly that). Deriving it from the filesystem means a new package needs no
# edit here at all.
#
# Why named volumes at all: a bind mount of 150k+ files is slow on macOS and
# on Codespaces' overlay, and a host directory that is empty (a fresh clone,
# or a git worktree) otherwise shadows what the container built.
#
# Usage: generate-compose-volumes.sh [output-path]
#   Defaults to .devcontainer/docker-compose.volumes.yml. The tests pass a
#   temporary path so they can check the output without touching the repo.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT="${1:-$SCRIPT_DIR/../docker-compose.volumes.yml}"

# Maps a workspace's `build` script to the directory it writes. Kept as a
# visible decision rather than a glob: a workspace whose build tool is not
# listed here is reported below and named by
# tests/architecture/devcontainer-agrees-with-the-repo.test.ts.
build_output_dir() {
  case "$1" in
    *"next build"*) echo ".next" ;;
    *"docusaurus build"*) echo "build" ;;
    *"tsc"* | *"nest build"* | *"swc"*) echo "dist" ;;
    *) echo "" ;;
  esac
}

# The build script of a workspace, or empty when it has none.
#
# Text, not JSON parsing, and on purpose: this runs on the *host* — your
# laptop, or the Codespaces VM — before any container exists, so it can assume
# a shell and nothing else. Not even node: the host is not required to have
# the toolchain this container is here to provide.
#
# The cost is a parse that a reformatted package.json could fool. That is
# covered rather than hoped about: tests/architecture/devcontainer-agrees-with-
# the-repo.test.ts enumerates the workspaces with a real JSON parser and fails
# when one of them has no volume here.
build_script_of() {
  sed -n 's/.*"build"[[:space:]]*:[[:space:]]*"\(.*\)".*/\1/p' "$1" | head -1
}

mounts="      - ws_node_modules:/workspace/node_modules
"
declarations="  ws_node_modules:
"
unmapped=""
seen_slugs=""
count=1

for parent in packages apps; do
  [ -d "$ROOT_DIR/$parent" ] || continue

  for workspace_dir in "$ROOT_DIR/$parent"/*/; do
    [ -f "${workspace_dir}package.json" ] || continue

    workspace="$(basename "$workspace_dir")"
    build_script="$(build_script_of "${workspace_dir}package.json")"
    [ -n "$build_script" ] || continue

    output_dir="$(build_output_dir "$build_script")"
    if [ -z "$output_dir" ]; then
      unmapped="$unmapped $parent/$workspace"
      continue
    fi

    # Docker volume names take no hyphens or dots. Collapsing both to `_`
    # is not injective — `rag-core` and `rag.core` would land on the same
    # name and then silently *share* one volume, each overwriting the other's
    # build output. No two workspaces collide today; this refuses to generate
    # rather than let one appear later as an unreproducible build.
    slug="$(echo "${parent}_${workspace}_${output_dir}" | tr '.-' '__')"
    case " $seen_slugs " in
      *" $slug "*)
        echo "ERROR: $parent/$workspace normalizes to a volume name already in use (ws_$slug)." >&2
        echo "       Rename the workspace, or make the slug injective in $(basename "$0")." >&2
        exit 1
        ;;
    esac
    seen_slugs="$seen_slugs $slug"
    mounts="$mounts      - ws_${slug}:/workspace/${parent}/${workspace}/${output_dir}
"
    declarations="$declarations  ws_${slug}:
"
    count=$((count + 1))
  done
done

cat > "$OUTPUT" <<EOF
# Generated by .devcontainer/scripts/generate-compose-volumes.sh — do not edit.
# Regenerated on every container start (devcontainer.json's initializeCommand),
# so a workspace added after this file was written is picked up on the next
# "Reopen in Container" with no edit here.
services:
  workspace:
    volumes:
$mounts
volumes:
$declarations
EOF

echo "Generated $(basename "$OUTPUT") with $count volumes."
if [ -n "$unmapped" ]; then
  echo "WARNING: no output directory known for:$unmapped"
  echo "         Their build output stays on the bind mount, which still works but is slow."
  echo "         Add the build tool to build_output_dir() in $(basename "$0")."
fi
