import type { EncryptionSelection } from './encryption-provider';
import type { ConfigField, StorageSelection } from './storage-provider';

/**
 * The whole `ragen.config.ts`, rendered.
 *
 * This replaced patching a marked region in the cloned file, after that
 * approach produced four separate defects in a day: a substring search that
 * matched the end marker inside the start marker, a marker line that carried
 * explanatory prose and so matched nothing once the search was tightened, and
 * two duplicate-region layouts that each mangled the file in a different way.
 * Every one was a case of locating a region inside arbitrary text, and the
 * space of ways that goes wrong is not something a fixture can be trusted to
 * explore — the third defect reached CI precisely because every fixture
 * agreed with the others and none agreed with the file being shipped.
 *
 * Rendering the whole file removes the operation entirely. There is nothing
 * to find, nothing to preserve, and no malformed input: the installer writes
 * what it means.
 *
 * The cost is that this template must carry the groups the wizard never asks
 * about, and could drift from the file the repository ships. It cannot:
 * `ragen.config.ts` at the repository root **is generated from this function**
 * (`npm run config:template`), and
 * `tests/architecture/ragen-config-is-generated.test.ts` compares them. One
 * source, one artifact, checked — the same arrangement as the published
 * configuration reference.
 */

export const CONFIG_FILENAME = 'ragen.config.ts';

/**
 * A required field is typed `string`, so `process.env.X` alone does not
 * compile — it is `string | undefined`. The fallback is a blank rather than a
 * non-null assertion because a blank is *true*: the variable may genuinely be
 * missing, and every reader in `@ragenai/env` treats blank as unset, so the
 * boot-time check reports it instead of a `!` hiding it until something
 * dereferences undefined.
 */
function renderField({ field, envVar, required }: ConfigField): string {
  const value = required
    ? `process.env.${envVar} ?? ''`
    : `process.env.${envVar}`;
  return `    ${field}: ${value},`;
}

function renderGroup(
  group: string,
  provider: string,
  fields: ConfigField[],
  comment?: string,
): string[] {
  return [
    `  ${group}: {`,
    ...(comment ? [`    // ${comment}`] : []),
    `    provider: '${provider}',`,
    ...fields.map(renderField),
    '  },',
  ];
}

const HEADER = `import { defineConfig } from '@ragenai/env';

/**
 * The configuration this deployment was created with.
 *
 * Generated by \`create-ragen-app\`, which writes it once when the project is
 * scaffolded and never again — so in a scaffolded project this is yours to
 * edit.
 *
 * In the Ragen repository itself it is an artifact: regenerate it with
 * \`npm run config:template\` and make changes in
 * \`packages/create-ragen-app/src/config-template.ts\`, or the next scaffold
 * discards them.
 *
 * ADR-37 declined a \`ragen.config.ts\` the apps would *read* instead of the
 * environment, and that still holds: a secret does not belong in git, and
 * compose, the Dockerfiles and Railway only speak environment variables.
 * **Nothing reads this file at runtime.** It is the structure and the
 * defaulting, with every value still resolved from \`process.env\` — which is
 * why a fresh clone works with the minimum \`.env.local\` AGENTS.md documents,
 * and why the fallbacks below are the same ones the code already applies.
 *
 * What it is for: choosing a provider makes that provider's variables
 * mandatory *in the editor*. \`storage: { provider: 's3' }\` with no bucket does
 * not compile. \`npm run typecheck:config\` is what makes that real — without
 * it this file would be checked by nothing, since the repository has no root
 * \`tsconfig.json\`.
 *
 * The shapes come from \`packages/env/src/provider-seams.ts\` and
 * \`config-groups.ts\`, the same tables the boot-time check reads.
 */
export default defineConfig({
  database: {
    url:
      process.env.DATABASE_URL ??
      'postgresql://postgres:pass123@localhost:55432/ragen',
  },

  gateway: {
    // Every model call goes through LiteLLM (ADR-04).
    url: process.env.LITELLM_PROXY_URL ?? 'http://localhost:4000',
    masterKey: process.env.LITELLM_MASTER_KEY,
  },

  vectorStore: {
    // Qdrant is the only supported vector store (ADR-31).
    url: process.env.QDRANT_URL ?? 'http://localhost:6333',
    apiKey: process.env.QDRANT_API_KEY,
  },

  models: {
    chat: process.env.DEFAULT_MODEL ?? 'gemini-3-flash-preview',
    // Do not upgrade without approval — see AGENTS.md, "Model Defaults".
    rephrase: process.env.REPHRASE_MODEL ?? 'gemini-2.5-flash',
    summary: process.env.SUMMARY_MODEL ?? 'gemini-2.5-flash',
    embeddings: process.env.EMBEDDINGS_MODEL,
    // Changing this after documents exist invalidates the collection.
    vectorSize: process.env.VECTOR_SIZE,
  },

`;

export function renderRagenConfig(
  storage: StorageSelection,
  encryption: EncryptionSelection,
): string {
  const lines = [
    ...renderGroup(
      'storage',
      storage.provider,
      storage.configFields,
      storage.provider === 'local'
        ? 'ADR-27: local by default, so a fresh clone runs without a cloud account.'
        : undefined,
    ),
  ];

  if (encryption.provider !== 'none') {
    lines.push(
      '',
      ...renderGroup(
        'encryption',
        encryption.provider,
        encryption.configFields,
      ),
    );
  }

  return `${HEADER}${lines.join('\n')}\n});\n`;
}
