import { createSlice, type PayloadAction } from '@reduxjs/toolkit';

/**
 * One tool call currently being executed by an MCP connector. Rendered
 * as an inline chip above the streaming assistant message — similar to
 * Claude Desktop's "Using GitHub…" indicator. Keyed per-thread because
 * multiple threads can have independent in-flight tool calls.
 *
 * Lifecycle: `tool_call` SSE event → push into state. `tool_result` SSE
 * event → remove by `toolCallId`. A new user submit clears the whole
 * thread's list so stale entries from a crashed/aborted stream don't
 * linger.
 */
export type ActiveToolCall = {
  /** Globally unique ID generated by the AI SDK for this call. */
  toolCallId: string;
  /** Full prefixed tool name, e.g. `clickup__create_task`. */
  toolName: string;
  /**
   * Provider slug derived from the prefix, UPPERCASE to match
   * `McpConnectorProvider` enum values (`CLICKUP`, `GOOGLE_CALENDAR`,
   * etc.). Used for icon lookup.
   */
  provider: string;
  /** ISO timestamp — render can show "1.4s" elapsed if useful. */
  startedAt: string;
};

export type ToolCallsState = {
  /** Active (in-flight) tool calls keyed by threadId. */
  activeByThread: Record<string, ActiveToolCall[]>;
};

const initialState: ToolCallsState = {
  activeByThread: {},
};

export const toolCallsSlice = createSlice({
  name: 'toolCalls',
  initialState,
  reducers: {
    startToolCall: (
      state,
      action: PayloadAction<{ threadId: string; toolCall: ActiveToolCall }>,
    ) => {
      const { threadId, toolCall } = action.payload;
      const existing = state.activeByThread[threadId] ?? [];
      // Idempotent: if the same toolCallId re-fires (shouldn't, but
      // safe), replace rather than duplicate.
      const without = existing.filter(
        (c) => c.toolCallId !== toolCall.toolCallId,
      );
      state.activeByThread[threadId] = [...without, toolCall];
    },
    completeToolCall: (
      state,
      action: PayloadAction<{ threadId: string; toolCallId: string }>,
    ) => {
      const { threadId, toolCallId } = action.payload;
      const existing = state.activeByThread[threadId];
      if (!existing) {
        return;
      }
      state.activeByThread[threadId] = existing.filter(
        (c) => c.toolCallId !== toolCallId,
      );
    },
    clearToolCalls: (state, action: PayloadAction<{ threadId: string }>) => {
      delete state.activeByThread[action.payload.threadId];
    },
  },
});

export const { startToolCall, completeToolCall, clearToolCalls } =
  toolCallsSlice.actions;

export default toolCallsSlice.reducer;
