import { createSlice, type PayloadAction } from '@reduxjs/toolkit';

/**
 * One pending tool approval — displayed inline in the assistant's
 * paused message as a ToolConfirmationCard with Approve / Deny buttons.
 * Scoped per-thread because multiple threads can have independent
 * pending approvals at the same time.
 */
export type PendingToolApproval = {
  /** Globally unique ID generated by the AI SDK for this approval request. */
  approvalId: string;
  /** The tool call the user is being asked to approve. */
  toolCallId: string;
  /** Full tool name including provider prefix, e.g. `google_calendar__gcal_create_event`. */
  toolName: string;
  /** Provider slug derived from the tool name, e.g. `google_calendar`. */
  provider: string;
  /** ISO timestamp for when this approval was surfaced. Used to filter stale state on reload. */
  createdAt: string;
};

export type ToolApprovalsState = {
  /**
   * Map keyed by threadId. Each thread holds its most recent pending
   * approval (there can only be one active paused tool call per turn —
   * the SDK can't issue multiple approvals in a single `streamText`
   * pass without the first being resolved). Cleared on next submit.
   */
  pendingByThread: Record<string, PendingToolApproval>;
};

const initialState: ToolApprovalsState = {
  pendingByThread: {},
};

export const toolApprovalsSlice = createSlice({
  name: 'toolApprovals',
  initialState,
  reducers: {
    setPendingApproval: (
      state,
      action: PayloadAction<{
        threadId: string;
        approval: PendingToolApproval;
      }>,
    ) => {
      state.pendingByThread[action.payload.threadId] = action.payload.approval;
    },
    clearPendingApproval: (
      state,
      action: PayloadAction<{ threadId: string }>,
    ) => {
      delete state.pendingByThread[action.payload.threadId];
    },
    clearAllPendingApprovals: (state) => {
      state.pendingByThread = {};
    },
  },
});

export const {
  setPendingApproval,
  clearPendingApproval,
  clearAllPendingApprovals,
} = toolApprovalsSlice.actions;

export default toolApprovalsSlice.reducer;
