// @deprecated — Import from @/features/organizations instead

export {
  saveTemperatureSetting,
  getTemperatureSetting,
  saveOpenaiAPIKey,
  getOpenaiAPIKey,
  saveAnthropicAPIKey,
  getAnthropicAPIKey,
  saveGoogleAPIKey,
  getGoogleAPIKey,
  saveBedrockCredentials,
  getBedrockCredentials,
  saveOllamaHost,
  getOllamaHost,
  saveOpenrouterAPIKey,
  getOpenrouterAPIKey,
  saveFireworksAPIKey,
  getFireworksAPIKey,
  saveAzureOpenAICredentials,
  getAzureOpenAICredentials,
  saveModel,
  getModel,
  saveAssistantPrompt,
  getAssistantPrompt,
  saveMaxDocumentsToRetrieve,
  getMaxDocumentsToRetrieve,
  saveVoiceId,
  getVoiceId,
  getAllSettings,
} from '@/features/organizations/services/organization-settings';
