import './global.css';

import { Inter } from 'next/font/google';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

type Props = {
  children: React.ReactNode;
  params: {
    locale: string;
  };
};

const inter = Inter({ subsets: ['latin'] });

export default function LocaleLayout({ children, params: { locale } }: Props) {
  return (
    <html lang={locale} className="h-full" suppressHydrationWarning>
      <body className={`${inter.className} h-full`}>{children}</body>
    </html>
  );
}
