name: E2E Tests

env:
  NEXT_PUBLIC_API_URL: 'http://example.com'
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  API_BASE_URL: ${{ secrets.API_BASE_URL }}
  DATABASE_DIRECT_URL: ${{ secrets.DATABASE_DIRECT_URL }}
  SUPABASE_API_URL: ${{ secrets.SUPABASE_API_URL }}
  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
  SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
  CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
  CLERK_WEBHOOK_SIGNING_SECRET: ${{ secrets.CLERK_WEBHOOK_SIGNING_SECRET }}
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
  NEXT_PUBLIC_CLERK_SIGN_IN_URL: ${{ vars.NEXT_PUBLIC_CLERK_SIGN_IN_URL }}
  NEXT_PUBLIC_CLERK_SIGN_UP_URL: ${{ vars.NEXT_PUBLIC_CLERK_SIGN_UP_URL }}
  LANGCHAIN_API_KEY: 'e2e'
  LANGCHAIN_ENDPOINT: 'http://example.com'
  LANGCHAIN_PROJECT: 'e2e'
  REDIS_URL: ${{ secrets.REDIS_URL }}
  SECRET_KEY: 'dummy'
  TARGET_ENV: 'test'
  TEMPORAL_SERVER_ADDRESS: 'http://example.com'
  TEMPORAL_NAMESPACE: 'ci'
  TEMPORAL_CERT: 'dummy'
  TEMPORAL_KEY: 'dummy'
  TESTS_CLERK_USER_EMAIL: ${{ vars.TESTS_CLERK_USER_EMAIL }}
  TESTS_CLERK_USER_PASSWORD: ${{ vars.TESTS_CLERK_USER_PASSWORD }}
  TESTS_CLERK_USER_USERNAME: ${{ vars.TESTS_CLERK_USER_USERNAME }}
  QDRANT_URL: 'http://example.com'
  RESEND_API_KEY: 'dummy'
  RESEND_DEFAULT_AUDIENCE_ID: 'dummy'
  AWS_REGION: 'dummy'
  AWS_ACCESS_KEY_ID: 'dummy'
  AWS_SECRET_ACCESS_KEY: 'dummy'
  AWS_DOCUMENTS_BUCKET: 'dummy'
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: 'dummy'
  STRIPE_SECRET_KEY: 'dummy'
  STRIPE_WEBHOOK_SECRET: 'dummy'
  FIRECRAWL_API_KEY: 'dummy'
  FEATURE_FLAG_SHOW_MODEL_API_KEY: 1
  FEATURE_FLAG_MODEL_SELECT: 1
  DEFAULT_MODEL_PROVIDER: 'google'
  DEFAULT_MODEL: 'gemini-2.0-flash'
  GOOGLE_API_KEY: 'dummy'
  PUSHER_APP_ID: 'dummy'
  PUSHER_KEY: 'dummy'
  PUSHER_SECRET: 'dummy'
  NEXT_PUBLIC_PUSHER_KEY: 'dummy'

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
jobs:
  test-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').packages[''].devDependencies['@playwright/test'])")" >> $GITHUB_ENV

      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - run: npx playwright install-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Run Playwright tests
        run: npx playwright test
        env:
          NEXT_PUBLIC_ENABLE_MSW_MOCKING: 'enabled'
          NEXT_PUBLIC_TEST_ENV: 'enabled'
          CLERK_JWT_KEY: 'dummy'

      - name: Publish report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Publish Test Summary Results
        run: npx github-actions-ctrf ctrf/ctrf-report.json
